base/urls.py
from django.urls import path

from .views import base_views, board_views, comment_views, vote_views

app_name = 'base'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:board_id>/', base_views.detail, name='detail'),

    # board_views.py
    path('board/create', board_views.board_create, name='board_create'),
    path('board/modify/<int:board_id>/', board_views.board_modify, name='board_modify'),
    path('board/delete/<int:board_id>/', board_views.board_delete, name='board_delete'),

    # comment_views.py
    path('comment/create/<int:board_id>', comment_views.comment_create, name='comment_create'),
    path('comment/modify/<int:comment_id>/', comment_views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', comment_views.comment_delete, name='comment_delete'),

    path('comment/reply/create/<int:comment_id>', comment_views.reply_create, name='reply_create'),
    path('comment/reply/modify/<int:reply_id>', comment_views.reply_modify, name='reply_modify'),
    path('comment/reply/delete/<int:reply_id>', comment_views.reply_delete, name='reply_delete'),

    # vote_views.py
    path('vote/board/<int:board_id>/', vote_views.vote_board, name='vote_board'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=200)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name


class Boards(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_id_board')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_board', blank=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, default='1')
    view_count = models.IntegerField(null=True, blank=True, default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Boards"


class Comment(models.Model):
    board = models.ForeignKey(Boards, on_delete=models.CASCADE, null=False, blank=False)
    content = models.TextField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)


class Reply(models.Model):
    content = models.TextField(null=True)
    board = models.ForeignKey(Boards, on_delete=models.CASCADE, null=True, blank=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True, blank=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

base/forms.py
from django import forms
from base.models import Boards, Comment, Reply, Category

class BoardForm(forms.ModelForm):
    class Meta:
        model = Boards
        fields = ['category', 'title', 'content']
        labels = {
            'category': '분류',
            'title': '제목',
            'content': '내용',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

base/views/base_views.py
from django.shortcuts import render, get_object_or_404
from ..models import Boards
from django.core.paginator import Paginator
from django.db.models import Q, Count


def index(request):
    page = request.GET.get('page', '1')
    cate = request.GET.get('cate', '전체')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')

    if cate == '자유':
        board_list = Boards.objects.all().filter(category = "1")
    elif cate == '정보':
        board_list = Boards.objects.all().filter(category = "2")
    elif cate == '질문':
        board_list = Boards.objects.all().filter(category = "3")
    else:  # all
        board_list = Boards.objects.all().order_by('-create_date')

    if kw:
        board_list = board_list.filter(
            Q(title__icontains = kw) |
            Q(content__icontains = kw) |
            Q(user_id__username__icontains = kw) |
            Q(comment__content__icontains = kw) |
            Q(comment__user_id__username__icontains = kw)
        ).distinct()

    board_list = board_list.annotate(
        num_voter = Count('voter', distinct = True),
        num_comment = Count('comment', distinct = True) + Count('reply', distinct = True) + Count('comment__reply',
                                                                                                  distinct = True))
    if so == 'recommend':
        board_list = board_list.order_by('-num_voter', '-create_date')
    elif so == 'popular':
        board_list = board_list.order_by('-num_comment', '-create_date')
    else:  # recent
        board_list = board_list.order_by('-create_date')

    paginator = Paginator(board_list, 13)
    page_obj = paginator.get_page(page)

    context = {'board_list': page_obj, 'cate': cate, 'page': page, 'kw': kw, 'so': so}

    return render(request, 'base/board_list.html', context)


def detail(request, board_id):
    board = get_object_or_404(Boards, pk = board_id)

    board.view_count += 1
    board.save()

    context = {'board': board}
    return render(request, 'base/board_detail.html', context)

base/views/board_views.py
from django.core import paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from ..models import Boards, Category
from ..forms import BoardForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required(login_url='accounts:login')
def board_create(request):
    # 등록폼으로 처리
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.user_id = request.user
            board.create_date = timezone.now()
            board.save()
            return redirect('base:index')
    # 게시글등록 버튼을 누를 경우
    else:
        form = BoardForm()

    context = {'form': form}
    return render(request, 'base/board_form.html', context)


@login_required(login_url='accounts:login')
def board_modify(request, board_id):
    board = get_object_or_404(Boards, pk=board_id)
    if request.user != board.user_id:
        messages.error(request, '수정권한이 없습니다')
        return redirect('base:detail', board_id=board.id)

    if request.method == "POST":
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save(commit=False)
            board.modify_date = timezone.now()
            board.save()
            return redirect('base:detail', board_id=board.id)
    else:
        form = BoardForm(instance=board)
    context = {'form': form}
    return render(request, 'base/board_form.html', context)

@login_required(login_url='accounts:login')
def board_delete(request, board_id):
    board = get_object_or_404(Boards, pk=board_id)
    if request.user != board.user_id:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('base:detail', board_id=board.id)
    board.delete()
    return redirect('base:index')

base/views/comment_views.py
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from django.utils import timezone
from ..models import Boards, Comment, Reply
from ..forms import CommentForm, ReplyForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required(login_url='accounts:login')
def comment_create(request, board_id):
    board = get_object_or_404(Boards, pk=board_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user_id = request.user
            comment.create_date = timezone.now()
            comment.board = board
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('base:detail', board_id=board.id), comment.id))
    else:
        form = CommentForm()
    context = {'board': board, 'form': form}
    return render(request, 'base/board_detail.html', context)

@login_required(login_url='accounts:login')
def comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.user_id:
        messages.error(request, '수정권한이 없습니다')
        return redirect('base:detail', board_id=comment.board.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('base:detail', board_id=comment.board.id), comment.id))

    else:
        form = CommentForm(instance=comment)
    context = {'comment': comment, 'form': form}
    return render(request, 'base/comment_form.html', context)

@login_required(login_url='accounts:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.user_id:
        messages.error(request, '삭제권한이 없습니다')
    else:
        comment.delete()
    return redirect('base:detail', board_id=comment.board.id)

@login_required(login_url='accounts:login')
def reply_create(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user_id = request.user
            reply.create_date = timezone.now()
            reply.board = comment.board
            reply.comment = comment
            reply.save()

            return redirect('{}#reply_{}'.format(
                resolve_url('base:detail', board_id=reply.board.id), reply.id))
    else:
        form = ReplyForm()
    context = {'form': form}
    return render(request, 'base/reply_form.html', context)

@login_required(login_url='accounts:login')
def reply_modify(request, reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)
    if request.user != reply.user_id:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('base:detail', board_id=reply.board.id)

    if request.method == "POST":
        form = ReplyForm(request.POST, instance=reply)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.modify_date = timezone.now()
            reply.save()
            return redirect('{}#reply_{}'.format(
                resolve_url('base:detail', board_id=reply.board.id), reply.id))
    else:
        form = ReplyForm(instance=reply)
    context = {'form': form}
    return render(request, 'base/comment_form.html', context)

@login_required(login_url='accounts:login')
def reply_delete(request, reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)
    if request.user != reply.user_id:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('base:detail', board_id=reply.board.id)
    else:
        reply.delete()
    return redirect('base:detail', board_id=reply.board.id)

base/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Boards


@login_required(login_url='accounts:login')
def vote_board(request, board_id):
    board = get_object_or_404(Boards, pk=board_id)
    if request.user == board.user_id:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        board.voter.add(request.user)
    return redirect('base:detail', board_id=board.id)

templates/base/board_detail.html
{% extends 'base.html' %}
{% load base_filter %}
{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<div class="container my-3">
    <!--경고문-->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}

    <td>{{ board.category }}</td>
    <h2 class="border-bottom py-2">{{ board.title }}</h2>

    <!-- 추천 -->
    <div class="row my-3">
        <div class="col-1">
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ board.voter.count }}</div>
            <a href="#" data-uri="{% url 'base:vote_board' board.id  %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">

    <!--글표시-->
        <div class="card">
            <div class="card-body">
            <div class="card-text">{{ board.content|mark }}</div>
            <div class="d-flex justify-content-end">
                {% if board.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">수정됨</div>
                    <div>{{ board.modify_date }}</div>
                </div>
                {% endif %}
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ board.user_id.username }}</div>
                    <div> {{ board.create_date }} </div>
                    <div> 조회 {{ board.view_count }} </div>
                </div>
            </div>

            {% if request.user == board.user_id %}
            <div class="my-3">
            <a href="{% url 'base:board_modify' board.id  %}"
               class="btn btn-sm btn-outline-secondary">수정</a>

            <a href="#" class="delete btn btn-sm btn-outline-secondary"
                data-uri="{% url 'base:board_delete' board.id  %}">삭제</a>
            </div>
            {% endif %}

            </div>
        </div>
        </div>
    </div>


    <!--댓글표시-->
    <h5 class="border-bottom my-2 py-2">{{ board.comment_set.count|add:board.reply_set.count }} 개의 댓글</h5>
    {% for comment in board.comment_set.all %}
    <a name="comment_{{ comment.id }}"></a>
        <div class="card my-2 py-2">
            <div class="card-body">
                    <div class="card-text">{{ comment.content|mark }}</div>
                    <div class="d-flex justify-content-end">
                        {% if comment.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ comment.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ comment.user_id }}</div>
                            <div>{{ comment.create_date }}</div>
                        </div>
                    </div>
                {% if request.user == comment.user_id %}
                <div class="my-3">
                    <a href="{% url 'base:comment_modify' comment.id  %}"
                        class="btn btn-sm btn-outline-secondary">수정</a>
                    <a href="#" class="delete btn btn-sm btn-outline-secondary "
                        data-uri="{% url 'base:comment_delete' comment.id  %}">삭제</a>
                </div>
                {% endif %}


                <!--대댓글표시-->
            {% if comment.reply_set.count > 0 %}
            <div class="mt-3">
            {% for reply in comment.reply_set.all %}
                <a name="reply_{{ reply.id }}"></a>
                <div class="reply py-2 text-muted">
                    <span style="white-space: pre-wrap;"> {{ reply.content }}</span>
                    <span>
                        - {{ reply.user_id }}, {{ reply.create_date }}
                        {% if reply.modify_date %}
                        (수정:{{ reply.modify_date }})
                        {% endif %}
                    </span>

                    {% if request.user == comment.user_id %}
                    <a href="{% url 'base:reply_modify' reply.id  %}" class="small">수정</a>,
                    <a href="#" class="small delete"
                       data-uri="{% url 'base:reply_delete' reply.id  %}">삭제</a>
                    {% endif %}
                </div>

            {% endfor %}
            </div>
            {% endif %}

                <div>
                    <a href="{% url 'base:reply_create' comment.id  %}"
                       class="small"><small>댓글 추가</small></a>
                </div>

            </div>
        </div>
    {% endfor %}
</div>

<div class="container my-3">
    <!--댓글작성창-->
    <form action="{% url 'base:comment_create' board.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea  {% if not user.is_authenticated %}disabled{% endif %}
                       name="content" id="content" class="form-control" rows="3"></textarea>
        </div>
        <input type="submit" value="댓글등록" class="btn btn-primary">
    </form>

</div>
{% endblock %}

<!--삭제경고문-->
{% block script %}
<script type='text/javascript'>
    $(document).ready(function(){
        $(".delete").on('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });

        $(".recommend").on('click', function() {
            if(confirm("정말로 추천하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
    });
</script>
{% endblock %}

templates/base/board_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container" xmlns="http://www.w3.org/1999/html">
    <h5 class="my-3 border-bottom pb-2">글등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}

        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}

        <div class="row justify-content-between my-3">
            <div class="col-2">
                <label for="category">분류</label>
                <select class="form-control" name="category" id="category">
                    <option value="" selected>---------</option>
                    <option value="1">자유</option>
                    <option value="2">정보</option>
                    <option value="3">질문</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="title">제목</label>
            <input type="text" class="form-control" name="title" id="title"
                   value="{{ form.title.value|default_if_none:'' }}">
        </div>

        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

templates/base/board_list.html
{% extends 'base.html' %}
{% load base_filter %}
{% block content %}

{% load static %}


<div class="container mt-3">
    <div class="row justify-content-between mb-3">
        <div class="col-3">
            <select class="form-control so">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
                <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>
                <option value="popular" {% if so == 'popular' %}selected{% endif %}>인기순</option>
            </select>
        </div>
        <div class="col-6 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-sm table-hover">
            <thead>

            <tr class="text-center thead-dark">
                <th>분류</th>
                <th>번호</th>
                <th>추천</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
                <th>조회수</th>
            </tr>

            </thead>
            <tbody>

            {% if board_list %}
            {% for Boards in board_list %}
            <tr class="text-center">
                <td class="align-middle">
                    {{ Boards.category }}
                </td>
                <td class="small align-middle">
                    {{ board_list.paginator.count|sub:board_list.start_index|sub:forloop.counter0|add:1 }}
                </td>
                <td class="align-middle">
                {% if Boards.voter.all.count > 0 %}
                <span class="badge badge-warning px-2 py-1">{{ Boards.voter.all.count }}</span>
                {% endif %}
                </td>
                <td class="text-center align-middle">
                    <a href="{% url 'base:detail' Boards.id %}">{{ Boards.title }}</a>
                    {% if Boards.comment_set.count > 0 %}
                    <span class="text-danger small ml-2">{{ Boards.comment_set.count|add:Boards.reply_set.count }}</span>
                    {% endif %}
                </td>
                <td class="small align-middle">
                    {{ Boards.user_id.username }}
                </td>
                <td class="align-middle" style="font-size:0.75em">
                    {{ Boards.create_date }}
                </td>
                <td class="small align-middle">
                    {{ Boards.view_count }}
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">글이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
    </div>

    <ul class="pagination justify-content-center">
        {% if board_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ board_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}

        {% for page_number in board_list.paginator.page_range %}
        {% if page_number >= board_list.number|add:-5 and page_number <= board_list.number|add:5 %}

            {% if page_number == board_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}

        {% if board_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ board_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>

    <a href="{% url 'base:board_create' %}" class="btn btn-primary">게시글 등록</a>
</div>

<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
    <input type="hidden" id="cate" name="cate" value="{{ cate }}">
</form>

{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);
        $("#searchForm").submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });

    $(".cate").on('click', function() {
        $("#cate").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

templates/base/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/base/reply_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}