accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.signup, name="signup"),
]

base/urls.py
from django.urls import path

from .views import base_views, board_views, comment_views, vote_views

app_name = 'base'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:board_id>/', base_views.detail, name='detail'),

    # board_views.py
    path('board/create', board_views.board_create, name='board_create'),
    path('board/modify/<int:board_id>/', board_views.board_modify, name='board_modify'),
    path('board/delete/<int:board_id>/', board_views.board_delete, name='board_delete'),

    # comment_views.py
    path('comment/create/<int:board_id>', comment_views.comment_create, name='comment_create'),
    path('comment/modify/<int:comment_id>/', comment_views.comment_modify, name='comment_modify'),
    path('comment/delete/<int:comment_id>/', comment_views.comment_delete, name='comment_delete'),

    path('comment/reply/create/<int:comment_id>', comment_views.reply_create, name='reply_create'),
    path('comment/reply/modify/<int:reply_id>', comment_views.reply_modify, name='reply_modify'),
    path('comment/reply/delete/<int:reply_id>', comment_views.reply_delete, name='reply_delete'),

    # vote_views.py
    path('vote/board/<int:board_id>/', vote_views.vote_board, name='vote_board'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=200)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name


class Boards(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_id_board')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_board', blank=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, default='1')
    view_count = models.IntegerField(null=True, blank=True, default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Boards"


class Comment(models.Model):
    board = models.ForeignKey(Boards, on_delete=models.CASCADE, null=False, blank=False)
    content = models.TextField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)


class Reply(models.Model):
    content = models.TextField(null=True)
    board = models.ForeignKey(Boards, on_delete=models.CASCADE, null=True, blank=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True, blank=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

base/forms.py
from django import forms
from base.models import Boards, Comment, Reply, Category

class BoardForm(forms.ModelForm):
    class Meta:
        model = Boards
        fields = ['category', 'title', 'content']
        labels = {
            'category': '분류',
            'title': '제목',
            'content': '내용',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

base/views/base_views.py
from django.shortcuts import render, get_object_or_404
from ..models import Boards
from django.core.paginator import Paginator
from django.db.models import Q, Count


def index(request):
    page = request.GET.get('page', '1')
    cate = request.GET.get('cate', '전체')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')

    if cate == '자유':
        board_list = Boards.objects.all().filter(category = "1")
    elif cate == '정보':
        board_list = Boards.objects.all().filter(category = "2")
    elif cate == '질문':
        board_list = Boards.objects.all().filter(category = "3")
    else:  # all
        board_list = Boards.objects.all().order_by('-create_date')

    if kw:
        board_list = board_list.filter(
            Q(title__icontains = kw) |
            Q(content__icontains = kw) |
            Q(user_id__username__icontains = kw) |
            Q(comment__content__icontains = kw) |
            Q(comment__user_id__username__icontains = kw)
        ).distinct()

    board_list = board_list.annotate(
        num_voter = Count('voter', distinct = True),
        num_comment = Count('comment', distinct = True) + Count('reply', distinct = True) + Count('comment__reply',
                                                                                                  distinct = True))
    if so == 'recommend':
        board_list = board_list.order_by('-num_voter', '-create_date')
    elif so == 'popular':
        board_list = board_list.order_by('-num_comment', '-create_date')
    else:  # recent
        board_list = board_list.order_by('-create_date')

    paginator = Paginator(board_list, 13)
    page_obj = paginator.get_page(page)

    context = {'board_list': page_obj, 'cate': cate, 'page': page, 'kw': kw, 'so': so}

    return render(request, 'base/board_list.html', context)


def detail(request, board_id):
    board = get_object_or_404(Boards, pk = board_id)

    board.view_count += 1
    board.save()

    context = {'board': board}
    return render(request, 'base/board_detail.html', context)

base/views/board_views.py
from django.core import paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from ..models import Boards, Category
from ..forms import BoardForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required(login_url='accounts:login')
def board_create(request):
    # 등록폼으로 처리
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.user_id = request.user
            board.create_date = timezone.now()
            board.save()
            return redirect('base:index')
    # 게시글등록 버튼을 누를 경우
    else:
        form = BoardForm()

    context = {'form': form}
    return render(request, 'base/board_form.html', context)


@login_required(login_url='accounts:login')
def board_modify(request, board_id):
    board = get_object_or_404(Boards, pk=board_id)
    if request.user != board.user_id:
        messages.error(request, '수정권한이 없습니다')
        return redirect('base:detail', board_id=board.id)

    if request.method == "POST":
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save(commit=False)
            board.modify_date = timezone.now()
            board.save()
            return redirect('base:detail', board_id=board.id)
    else:
        form = BoardForm(instance=board)
    context = {'form': form}
    return render(request, 'base/board_form.html', context)

@login_required(login_url='accounts:login')
def board_delete(request, board_id):
    board = get_object_or_404(Boards, pk=board_id)
    if request.user != board.user_id:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('base:detail', board_id=board.id)
    board.delete()
    return redirect('base:index')

base/views/comment_views.py
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from django.utils import timezone
from ..models import Boards, Comment, Reply
from ..forms import CommentForm, ReplyForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required(login_url='accounts:login')
def comment_create(request, board_id):
    board = get_object_or_404(Boards, pk=board_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user_id = request.user
            comment.create_date = timezone.now()
            comment.board = board
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('base:detail', board_id=board.id), comment.id))
    else:
        form = CommentForm()
    context = {'board': board, 'form': form}
    return render(request, 'base/board_detail.html', context)

@login_required(login_url='accounts:login')
def comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.user_id:
        messages.error(request, '수정권한이 없습니다')
        return redirect('base:detail', board_id=comment.board.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(
                resolve_url('base:detail', board_id=comment.board.id), comment.id))

    else:
        form = CommentForm(instance=comment)
    context = {'comment': comment, 'form': form}
    return render(request, 'base/comment_form.html', context)

@login_required(login_url='accounts:login')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.user_id:
        messages.error(request, '삭제권한이 없습니다')
    else:
        comment.delete()
    return redirect('base:detail', board_id=comment.board.id)

@login_required(login_url='accounts:login')
def reply_create(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user_id = request.user
            reply.create_date = timezone.now()
            reply.board = comment.board
            reply.comment = comment
            reply.save()

            return redirect('{}#reply_{}'.format(
                resolve_url('base:detail', board_id=reply.board.id), reply.id))
    else:
        form = ReplyForm()
    context = {'form': form}
    return render(request, 'base/reply_form.html', context)

@login_required(login_url='accounts:login')
def reply_modify(request, reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)
    if request.user != reply.user_id:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('base:detail', board_id=reply.board.id)

    if request.method == "POST":
        form = ReplyForm(request.POST, instance=reply)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.modify_date = timezone.now()
            reply.save()
            return redirect('{}#reply_{}'.format(
                resolve_url('base:detail', board_id=reply.board.id), reply.id))
    else:
        form = ReplyForm(instance=reply)
    context = {'form': form}
    return render(request, 'base/comment_form.html', context)

@login_required(login_url='accounts:login')
def reply_delete(request, reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)
    if request.user != reply.user_id:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('base:detail', board_id=reply.board.id)
    else:
        reply.delete()
    return redirect('base:detail', board_id=reply.board.id)

base/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Boards


@login_required(login_url='accounts:login')
def vote_board(request, board_id):
    board = get_object_or_404(Boards, pk=board_id)
    if request.user == board.user_id:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        board.voter.add(request.user)
    return redirect('base:detail', board_id=board.id)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/x-icon" href="/static/img/favicon.ico">

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <title>Hello</title>
</head>
<body>

{% include "navbar.html" %}

<div class="container mt-3">
    <div class="row">
        <div class="col-sm-12 col-md-3 col-lg-2 p-2">
            {% include "sidebar.html" %}
        </div>
        <div class="col-sm-12 col-md-9 col-lg-10 p-2">
            <div id="content">
                <div class="content_block">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>
{% include "footer.html" %}

<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>

{% block script %}
{% endblock %}

</body>
</html>

templates/footer.html
<footer class="footer">
    <div class="container mt-3">
        <span class="text-muted">©2021 • JS.KR</span>
    </div>
</footer>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'base:index' %}">JS</a>

        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-align-justify"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item ">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'accounts:logout' %}">
                        <i class="fas fa-trophy"></i> {{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'accounts:login' %}"><i class="fas fa-trophy"></i> 로그인</a>
                    {% endif %}
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'accounts:login' %}"><i class="fas fa-user-plus"></i> 회원가입</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/sidebar.html
<nav id="sidebar" class="border-top border-secondary">
    <div class="list-group">
        <button type="button" value="전체" class="cate rounded-0 list-group-item list-group-item-action
            list-group-item-light {% if cate == '전체' %} active {% endif %}">전체</button>
        <button type="button" value="자유" class="cate rounded-0 list-group-item list-group-item-action
            list-group-item-light {% if cate == '자유' %} active {% endif %}">자유</button>
        <button type="button" value="정보" class="cate rounded-0 list-group-item list-group-item-action
            list-group-item-light {% if cate == '정보' %} active {% endif %}">정보</button>
        <button type="button" value="질문" class="cate rounded-0 list-group-item list-group-item-action
            list-group-item-light {% if cate == '질문' %} active {% endif %}">질문</button>
    </div>
</nav>